=== driele-torres/AnimeWebCatalog/web/AnimeSchema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
	<xs:element name="animecatalogue">
	<xs:annotation>
		<xs:documentation>
		Created by: Driele Torres Elaine Portela Kelly Correia This file contains all information that will be used in this project.
		</xs:documentation>
	</xs:annotation>
	<xs:complexType>
		<xs:sequence>
			<xs:element name="info">
				<xs:complexType>
					<xs:sequence>
						<xs:element type="xs:string" name="about"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="animes">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="collection" maxOccurs="26" minOccurs="1">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="anime" maxOccurs="unbounded" minOccurs="0">
										<xs:complexType>
											<xs:sequence>
												<xs:element type="xs:string" name="title"/>
												<xs:element name="animegenres" maxOccurs="1" minOccurs="1">
													<xs:complexType>
														<xs:sequence>
															<xs:element name="animegenre" maxOccurs="unbounded" minOccurs="1">
																<xs:complexType>
																	<xs:simpleContent>
																		<xs:extension base="xs:string">
																			<xs:attribute type="xs:string" name="id" use="required"/>
																		</xs:extension>
																	</xs:simpleContent>
																</xs:complexType>
															</xs:element>
														</xs:sequence>
													</xs:complexType>
												</xs:element>
												<xs:element type="xs:string" name="type"/>
												<xs:element type="xs:short" name="year"/>
												<xs:element type="xs:string" name="episodes"/>
												<xs:element type="xs:string" name="description"/>
											</xs:sequence>
											<xs:attribute type="xs:string" name="id" use="required"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:attribute type="xs:string" name="letter" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="characters">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="ccollection" maxOccurs="26" minOccurs="1">
							<xs:complexType>
								<xs:sequence maxOccurs="unbounded" minOccurs="0">
									<xs:element name="character">
										<xs:complexType>
											<xs:sequence>
												<xs:element type="xs:string" name="name"/>
												<xs:element type="xs:string" name="voice"/>
												<xs:element type="xs:string" name="idanime"/>
											</xs:sequence>
											<xs:attribute type="xs:byte" name="id" use="required"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:attribute type="xs:string" name="letter" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="genres">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="gcollection" maxOccurs="26" minOccurs="1">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="genre" maxOccurs="unbounded" minOccurs="0">
										<xs:complexType>
											<xs:sequence>
												<xs:element type="xs:string" name="genrename"/>
												<xs:element type="xs:string" name="information"/>
											</xs:sequence>
											<xs:attribute type="xs:string" name="id" use="required"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:attribute type="xs:string" name="letter" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	</xs:element>
	</xs:schema>

=== driele-torres/AnimeWebCatalog/web/AnimeCatalogue.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
        Created by:
                Driele Torres
                Elaine Portela
                Kelly Correia
        This file contains all information that will be used in this project. 
-->

<animecatalogue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation='AnimeSchema.xsd'>	

    <info>
        <about>
            Here you can find a list of some animes we like and some information about them as description, year of release, title and characters.
            And some information about the anime genres.
            This site was developed as project of Web Development in order to apply our knowledge about this module.
            We had supervision of Eugene McLaughlin .
        </about>
    </info>
	
    <animes>
        <collection letter="A">
            <anime id="A1">
                <title>A-Channel</title>
                <animegenres> 
                    <animegenre id='c2'/>
                    <animegenre id='s2'/>
                    <animegenre id='s9'/>  
                    <animegenre id='s4'/>
                </animegenres>
                <type>TV</type>
                <year>2011</year>
                <episodes>12</episodes>
                <description>
                    Tooru and Run have been best friends forever, so when Tooru learns that she's managed to get into the same high school as Run, she runs to tell her… only to find Run in a compromising position with yet another girl, Yuko. Needless to say, that makes things a bit awkward at school, with Tooru fending off those who might be interested in Run while Yuko and their other girlfriend, Nagi, have to deal with Run's own penchant for drama. 
                </description>
            </anime>

            <anime id="A2">
                <title>Accel World</title>
                <animegenres> 
                    <animegenre id='a1'/> 
                    <animegenre id='r1'/>
                    <animegenre id='s2'/>  
                    <animegenre id='s3'/>
                    <animegenre id='s7'/>
                </animegenres>
                <type>TV</type>
                <year>2012</year>
                <episodes>24</episodes>
                <description>
                    The year is 2046. Haruyuki Arita is a young boy who finds himself on the lowest social rungs of his school. Ashamed of his miserable life, Haruyuki can only cope by indulging in virtual games. But that all changes when Kuroyukihime, the most popular girl in school, introduces him to a mysterious program called Brain Burst and a virtual reality called the Accel World. 
                </description>
            </anime>
			
            <anime id="A3">
                <title>Angel Beats</title>
				
                <animegenres> 
                    <animegenre id='a1'/>
                    <animegenre id='c2'/>
                    <animegenre id='d3'/>  
                    <animegenre id='s14'/>
                </animegenres>
				
                <type>TV</type>
                <year>2010</year>
                <episodes>13</episodes>
                <description>
                    Otonashi awakens only to learn he is dead. A rifle-toting girl named Yuri explains that they are in the afterlife, and Otonashi realizes the only thing he can remember about himself is his title. Yuri tells him that she leads the Shinda Sekai Sensen (Afterlife Battlefront) and wages war against a girl named Tenshi. Unable to believe Yuri's claims that Tenshi is evil, Otonashi attempts to speak with her, but the encounter doesn't go as he intended.
                    Otonashi decides to join the SSS and battle Tenshi, but he finds himself oddly drawn to her. While trying to regain his memories and understand Tenshi, he gradually unravels the mysteries of the afterlif			
                </description>
            </anime>
			
            <anime id="A4">
                <title>Ao no Exorcist</title>
                <animegenres> 
                    <animegenre id='a1'/>
                    <animegenre id='f1'/>
                    <animegenre id='s7'/>  
                    <animegenre id='s14'/>
                </animegenres>			
                <type>TV</type>
                <year>2011</year>
                <episodes>25</episodes>
                <description>
                    Tohno Takaki and Shinohara Akari, two very close friends and classmates, are torn apart when Akari's family is transferred to another region of Japan due to her family's job. Despite separation, they continue to keep in touch through mail. When Takaki finds out that his family is also moving, he decides to meet with Akari one last time.
                    As years pass by, they continue down their own paths, their distance slowly growing wider and their contact with one another fades. Yet, they keep remembering one another and the times they have shared together, wondering if they will have the chance to meet once again.			
                </description>
            </anime>
		
        </collection>
		
        <collection letter="B">
			
            <anime id="B1">
                <title>Beck- Mongolian Chop Squad</title>
                <animegenres> 
                    <animegenre id='c2'/>
                    <animegenre id='d3'/>
                    <animegenre id='s7'/>  
                    <animegenre id='m5'/>
                    <animegenre id='s9'/>
                </animegenres>
				
                <type>TV</type>
                <year>2004</year>
                <episodes>26 </episodes>
                <description>
                    Tanaka Yukio, better known by his nickname Koyuki is a 14 year old who feels disconnected from life in general. Through the act of saving a mismatched dog, he meets guitarist Minami Ryuusuke, and becomes involved in Ryuusuke's new band BECK. Koyuki's life starts to change as the band struggles towards fame. 
                </description>
            </anime>
			
            <anime id="B2">
                <title>Byousoku 5 Centimeter</title>
                <animegenres> 
                    <animegenre id='r1'/>
                    <animegenre id='d3'/>
                    <animegenre id='s9'/>
                </animegenres>
				
                <type>Movie</type>
                <year>2007</year>
                <episodes>3</episodes>
                <description>
                    Tohno Takaki and Shinohara Akari, two very close friends and classmates, are torn apart when Akari's family is transferred to another region of Japan due to her family's job. Despite separation, they continue to keep in touch through mail. When Takaki finds out that his family is also moving, he decides to meet with Akari one last time.As years pass by, they continue down their own paths, their distance slowly growing wider and their contact with one another fades. Yet, they keep remembering one another and the times they have shared together, wondering if they will have the chance to meet once again.
                </description>
            </anime>
			
            <anime id="B3">
                <title>Bleach</title>
				
                <animegenres>
                    <animegenre id='a1'/>
                    <animegenre id='c2'/>
                    <animegenre id='s7'/>
                    <animegenre id='s13'/>
                    <animegenre id='s14'/>
                </animegenres>

                <type>TV</type>
                <year>2004</year>
                <episodes>366</episodes>
                <description>
                    15-year-old Kurosaki Ichigo is not your everyday high school student. He has from as far he can remember always had the ability to see ghosts and spirits. A fateful day arrives as Ichigo encounters the shinigami Kuchiki Rukia, who saves him and his family from a Hollow at the cost of injuring herself. During this encounter, with Rukia unable to defeat the hollow she transfers her shinigami powers into Ichigo. In the aftermath, unable to continue with her job, Rukia allows Ichigo to take on the role of a shinigami in her place as they together defeat the Hollows plaguing Ichigo's town.
                </description>
            </anime>
			
        </collection>
		
        <collection letter="C">
            <anime id="C1">
                <title>Cowboy Bebop</title>
				
                <animegenres>
                    <animegenre id='a1'/>
                    <animegenre id='a2'/>
                    <animegenre id='d3'/>
                    <animegenre id='s3'/>
                    <animegenre id='s11'/>
                </animegenres>
				
                <type>TV</type>
                <year>1998</year>
                <episodes>26</episodes>
                <description>
                    The year 2071 A.D. That future is now. Driven out of their terrestrial eden, humanity chose the stars as the final frontier. With the section-by-section collapse of the former nations a mixed jumble of races and peoples came. They spread to the stars, taking with them the now confused concepts of freedom, violence, illegality and love, where new rules and a new generation of outlaws came into being. People referred to them as Cowboys.
                    Meet Spike and Jet, a drifter and a retired cyborg cop who have started a bounty hunting operation. In the converted ship The Bebop, Spike and Jet search the galaxy for criminals with bounties on their heads. They meet a lot of unusual characters, including the unusually intelligent dog, Ein, and the voluptuous and vexing femme fatale, Faye Valentine.
                </description>
            </anime>
        </collection>
		
        <collection letter="D">
            <anime id="D1">
                <title>Death Note</title>
                <animegenres>
                    <animegenre id='m6'/>
                    <animegenre id='s14'/>
                    <animegenre id='p2'/>
